export const REGISTER_START = " REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

// export const REGISTER_USER_WITH_EMAIL = "REGISTER_USER_WITH_EMAIL";
// export const SET_REGISTER_USER_WITH_EMAIL = "SET_REGISTER_USER_WITH_EMAIL";
// export const GET_ALL_USERS = "GET_ALL_USERS";
// export const SET_GET_ALL_USERS = "SET_GET_ALL_USERS";
// export const SIGN_UP_USER_FIREBASE = "SIGN_UP_USER_FIREBASE";
// export const SET_SIGN_UP_USER_FIREBASE = "SET_SIGN_UP_USER_FIREBASE";

// export const AUTH_USER = "AUTH_USER";
// export const SET_AUTH_USER = "SET_AUTH_USER";
// export const LOG_OUT_USER = "LOG_OUT";
// export const SET_LOG_OUT_USER = "SET_LOG_OUT";
// export const LOGIN_USER = "LOGIN_USER";
// export const SET_LOGIN_USER = "SET_LOGIN_USER";
// export const CREATE_TANDA = "CREATE_TANDA";
// export const SET_CREATE_TANDA = "SET_CREATE_TANDA";
// export const GET_TANDA_CREATEDBY = "GET_TANDA_CREATEDBY";
// export const SET_GET_TANDA_CREATEDBY = "SET_GET_TANDA_CREATEDBY";
